### PR TITLE
Scan improvement and adjustment in the MuPixConverter

### PR DESCRIPTION
**Pull request by lhuth**
The PR resolves a feature of the scanning procedure: A scan can now be either started from the state `eudaq::State::CONF` or `eudaq::State::STOPPED`

### CODE REVIEW

**Comment by eyiliu** [comment]
Possiblely,  1 PR for MuPix/example,   another PR for  main is prefered

**Comment by lhuth** [comment]
Removed the changes in the MuPix part. 
The example is scan related and therefore kept.

**Comment by eyiliu** [comment]
@lhuth  I can not find an easy to merge/rebase/merge it with such conflicting (the endline).  Possiblly, you rebase them on master and fix.

**Comment by lhuth** [comment]
I updated the PR and rebased the new master. Hopefully, it can be merged now.

**Comment by lhuth** [comment]
nevermind, something went wrong on my side - I'll open a new one

**Pull request closed without merging**
