### PR TITLE
Remove MuPix8 module

### PR DESCRIPTION
**Pull request by stephanlachnit**
This is required for newer versions of the MuPix8_DAQ.

### CODE REVIEW

**Comment by lhuth** [comment]
Hi @stephanlachnit ,

this is deprecated - what about just deleting the complete module? :)

**Comment by stephanlachnit** [comment]
Like this? :)

**Comment by lhuth** [comment]
almost :) Missed the hard coded include_directories in `user/CMakeLists.txt`

**Comment by stephanlachnit** [comment]
Oh right, done

**Review by lhuth — APPROVED** [review]

**Pull request merged**
