### PR TITLE
clean up of the ni producer code.

### PR DESCRIPTION
**Pull request by RPeschke**
I started cleaning up the NI producer for this I used my new processor template class "proc". 

I think it looks much more streamlined like this what do you think?

### CODE REVIEW

**Comment by RPeschke** [comment]
@arummler can you help me understanding the errors of the CI checks?

**Comment by arummler** [comment]
I have to update the CI configuration, I will do it as soon as I have finished it within the V1.7 branch. Hopefully by next week.

**Comment by arummler** [comment]
Now master compiles again on CI (just the core library, switched off everything else as it needs to be investigated one by one). This PR went stale, there were a bunch of changes by Yi, could you please merge?

**Comment by dreyling** [comment]
I have changed the title, since not the Producer but the Converter Plugin was changed.

Richard, did you test this by converting data using the new code and by comparing the results?

@RPeschke @arummler

**Pull request merged**
