### PR TITLE
More development

### PR DESCRIPTION
**Pull request by andreypz**
* Modified startup scripts

### CODE REVIEW

**Comment by andreypz** [comment]
Sorry, again wrong repo...
Hmm, anybody knows how se set default pull request repo?

**Comment by eyiliu** [comment]
When you click  "new pull request", then a page shows with title "Comparing changes".
Just below this title. There are "base fork", "base", "head fork", "compare". You can change the repository and branch there.

**Comment by andreypz** [comment]
Sure, I get that.
But for every new pull request the default destination is always eudaq/eudaq. So, if I forget to change, it will pull there.
Is there a way to change the default destination to HGCDAQ/eudaq, ie to our fork default branch?

**Comment by eyiliu** [comment]
I do not know how.
I'd like to advice you to do the merge in your local clone, merge tdev-andrey2 branch to your HGCDAQ master.
And then push the merged master.

**Pull request closed without merging**
