### PR TITLE
Bump Version to v2.5.2

### PR DESCRIPTION
**Pull request by simonspa**
You first tagged v2.5.0 and then found the issue with ResizeSZ, so we need to re-release

### CODE REVIEW

**Comment by simonspa** [comment]
Hm, not sure that waveform thing has all in, I still get

```
Catchpoint 1 (exception thrown), 0x00007f1a85eac632 in __cxxabiv1::__cxa_throw (obj=0x4dc3c20, 
    tinfo=0x7f1a860011e8 <typeinfo for std::out_of_range>, dest=0x7f1a85ec1140 <std::out_of_range::~out_of_range()>)
    at /build/dkonst/gcc-clang-2/build/contrib/gcc-11.1.0/src/gcc/11.1.0/libstdc++-v3/libsupc++/eh_throw.cc:78
78	/build/dkonst/gcc-clang-2/build/contrib/gcc-11.1.0/src/gcc/11.1.0/libstdc++-v3/libsupc++/eh_throw.cc: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007f1a85eac632 in __cxxabiv1::__cxa_throw (obj=0x4dc3c20, tinfo=0x7f1a860011e8 <typeinfo for std::out_of_range>, 
    dest=0x7f1a85ec1140 <std::out_of_range::~out_of_range()>)
    at /build/dkonst/gcc-clang-2/build/contrib/gcc-11.1.0/src/gcc/11.1.0/libstdc++-v3/libsupc++/eh_throw.cc:78
#1  0x00007f1a85ea32ae in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold] ()
   from /cvmfs/sft.cern.ch/lcg/releases/gcc/11.1.0-e80bf/x86_64-centos7/lib64/libstdc++.so.6
#2  0x00007f1a88b29284 in std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::_M_range_check (this=<optimized out>, this=<optimized out>, __n=3)
    at /cvmfs/sft.cern.ch/lcg/releases/gcc/11.1.0-e80bf/x86_64-centos7/include/c++/11.1.0/bits/stl_vector.h:1073
#3  std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::at (__n=3, 
    this=<optimized out>) at /cvmfs/sft.cern.ch/lcg/releases/gcc/11.1.0-e80bf/x86_64-centos7/include/c++/11.1.0/bits/stl_vector.h:1112
#4  eudaq::StandardPlane::HasWaveform (this=this@entry=0x7ffffd1e0450, index=index@entry=3, frame=frame@entry=0)
    at /scratch/spanns/eudaq/main/lib/core/src/StandardPlane.cc:160
#5  0x00007f1a88de5d19 in corryvreckan::EventLoaderEUDAQ2::get_pixel_data (this=0x3b9b840, evt=..., plane_id=<optimized out>)
    at /scratch/spanns/corryvreckan/src/modules/EventLoaderEUDAQ2/EventLoaderEUDAQ2.cpp:494
```

in Corry when reading M26 data, even with eudaq `master`

**Comment by lhuth** [comment]
Hm, seems like we messed sth up there.... I'll take another look at it

**Comment by lhuth** [comment]
The changes are not implemented in the `SetupResults()` function, which merges the two MIMOSA frames (frame0 from pivot pixel on and frame1 until the pivot pixel)

**Comment by lhuth** [comment]
Master works fine for me on my local machine. So we should be good to go.

**Review by lhuth — APPROVED** [review]

**Pull request merged**
