### PR TITLE
TTree Converter code Implementation

### PR DESCRIPTION
**Pull request by msohailamjad**
Added the TTree Converter and an updated manual version to include TTree Converter documentation.

### CODE REVIEW

**Comment by arummler** [comment]
Please remove the files generated by Latex. Do we need FindROOT? Since 6.12 ROOT provides a ROOTconfig.

**Comment by msohailamjad** [comment]
Removed the Extra files. Wasn't able to compile without FindROOT so have kept it.

**Comment by arummler** [comment]
There are still superfluous files:
 EUDAQUserManual.glo
doc/src/Contributing.aux
doc/src/DataCollector.aux
doc/src/DataConverter.aux
doc/src/Installing.aux
doc/src/Integration.aux
doc/src/Introduction.aux
 doc/src/License.aux
 doc/src/Monitor.aux
doc/src/NewData.aux
 doc/src/PlatformIssue.aux
doc/src/Producers.aux
 doc/src/RunControl.aux
doc/src/Running.aux
...

**Comment by arummler** [comment]
Regarding root:
Which version are you using?
At which time of the cmake did it not find the config file?
Is ROOTSYS set?
Can you set CMAKE_PREFIX_PATH explicitly with -DC...= as explained in
https://root.cern.ch/how/integrate-root-my-project-cmake

**Comment by msohailamjad** [comment]
I have cleaned up and made a new commit without Latex generated files. 
Concerning ROOT, I have it installed with classic configure/make method, so I give it FindROOT.cmake as explained on the link you gave.

**Comment by msohailamjad** [comment]
Hi Andre, 
 Should I close this pull request and open a new one?

**Comment by arummler** [comment]
Hi, I do not have in the moment any time to really look over it. I just saw that you might have still missed superfluous files. Do we really want to have the pdf in the repo? Why is there a duplication of doc/src and doc/manual/src? You also might want to squash the delete commits. Just push to this PR.

**Comment by msohailamjad** [comment]
Merge conflict resolved.

**Pull request merged**
