### PR TITLE
Updates to Caribou Producer

### PR DESCRIPTION
**Pull request by simonspa**
This updates the Caribou producer with a few new features, chip support, bug fixes and a renovated CMake linking to the Peary software.

Please do not squash commits at merge, we will continue using this branch for the development of this producer.

### CODE REVIEW

**Comment by simonspa** [comment]
I'd be happy to get a tag v2.4.1 after this has been merged.

**Comment by arummler** [comment]
This is already fixed in PR #586 but I need someone to review it.

**Comment by simonspa** [comment]
Said, done. :)

**Comment by simonspa** [comment]
@eyiliu this is ready for review

**Comment by eyiliu** [comment]
@simonspa 
Please clean up a bit on the commit history. Thank you.

**Comment by simonspa** [comment]
@eyiliu I don't really see why this would be necessary. Anything in particular that is unacceptable for you?

**Comment by eyiliu** [comment]
It is not necessary for small project.  
It is not  unacceptable for me.
I would like to say it is good practice to clean up if possible. 
The user code will be anyhow approved and merged.

**Comment by simonspa** [comment]
Thanks for your quick response. If you don't insist I would like to keep the history as it is - mostly because there are several forks of this branch around which would lose track of upstream when rewriting history.

**Comment by simonspa** [comment]
Thanks a lot for merging. Could you tag v2.4.1 for me?

**Comment by simonspa** [comment]
Merging only adds a merge commit to `HEAD`. Compare the following:

### eudaq/eudaq/master
https://github.com/eudaq/eudaq/commits/master

image


### simonspa/eudaq/caribou
https://github.com/simonspa/eudaq/commits/caribou

image

**Comment by eyiliu** [comment]
Thank  you.  There was no other PR expect for your ones.

If you are not insisting to make tag today, we can include a few more changes from others in next few days into 2.4.1 . Eg. #585

**Comment by simonspa** [comment]
No, sure, in a few days it fine for me. Thanks for taking care of this!

**Pull request merged**
