### PR TITLE
Update to the CI scripts

### PR DESCRIPTION
**Pull request by freidt**
- Attempt to get rid of the VERSION variable

### CODE REVIEW

**Comment by freidt** [comment]
Please keep this PR open for the moment. I'd like to do some further tests. Thanks

**Comment by arummler** [comment]
The version variable was okay, just wanted to call it alpide_version or similar in order to avoid conflicts.

**Comment by arummler** [comment]
unsigoned ;)

**Comment by freidt** [comment]
fixed, just re-pushed the last commit to trigger the build again.

**Comment by freidt** [comment]
I'm done with my tests, PR can be merged once the checks are complete. Thanks!

**Pull request merged**
