### PR TITLE
Root interface based on 1p4 dev

### PR DESCRIPTION
**Pull request by RPeschke**
ROOT Interface

this pull request only contains files and changes necessary to build the ROOT Producer. 

it is more or less just a copy of the files from the old pull request without all the unnecessary changes to the core library

### CODE REVIEW

**Comment by simonspa** [comment]
Does this supersede #60?

**Comment by RPeschke** [comment]
yes it does.

**Comment by simonspa** [comment]
```
/home/spanns/ilcsoft/eudaq/producers/root/inc/ROOTProducer.h:7:20: fatal error: RTypes.h: No such file or directory
 #include "RTypes.h"
                    ^
compilation terminated.
```

root environment is sourced, other headers are found. Seems like a upper case typo, can you confirm for your root installation?

```
ll /opt/root/include/ | grep -i "rtypes"
-rw-rw-r-- 1 spanns spanns  18K Sep 10  2014 Rtypes.h

```

**Comment by simonspa** [comment]
Fixing this brings me to:

```
Building CXX object producers/root/CMakeFiles/ROOTProducer.dir/src/ROOTProducer.cpp.o
Building CXX object producers/root/CMakeFiles/ROOTProducer.dir/ROOTProducer_Dict.cxx.o
In file included from /opt/root/include/TObject.h:232:0,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.h:32,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:17:
/opt/root/include/TBuffer.h: In instantiation of ‘TBuffer& operator>>(TBuffer&, Tmpl*&) [with Tmpl = ROOTProducer::Producer_PImpl]’:
/home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:127:15:   required from here
/opt/root/include/TBuffer.h:378:47: error: invalid use of incomplete type ‘class ROOTProducer::Producer_PImpl’
    TClass *cl = TBuffer::GetClass(typeid(Tmpl));
                                               ^
In file included from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.h:34:0,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:17:
/home/spanns/ilcsoft/eudaq/producers/root/inc/ROOTProducer.h:100:8: error: forward declaration of ‘class ROOTProducer::Producer_PImpl’
  class Producer_PImpl;
        ^
In file included from /opt/root/include/TObject.h:232:0,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.h:32,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:17:
/opt/root/include/TBuffer.h: In instantiation of ‘TBuffer& operator<<(TBuffer&, const Tmpl*) [with Tmpl = ROOTProducer::Producer_PImpl]’:
/home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:132:15:   required from here
/opt/root/include/TBuffer.h:385:55: error: invalid use of incomplete type ‘class ROOTProducer::Producer_PImpl’
    TClass *cl = (obj) ? TBuffer::GetClass(typeid(*obj)) : 0;
                                                       ^
In file included from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.h:34:0,
                 from /home/spanns/ilcsoft/eudaq/build/producers/root/ROOTProducer_Dict.cxx:17:
/home/spanns/ilcsoft/eudaq/producers/root/inc/ROOTProducer.h:100:8: error: forward declaration of ‘class ROOTProducer::Producer_PImpl’
  class Producer_PImpl;
        ^
producers/root/CMakeFiles/ROOTProducer.dir/build.make:87: recipe for target 'producers/root/CMakeFiles/ROOTProducer.dir/ROOTProducer_Dict.cxx.o' failed

```

**Comment by simonspa** [comment]
Fixed and merged manually.

**Pull request merged**
