### PR TITLE
Build only converter

### PR DESCRIPTION
**Pull request by lhuth**
I've added a build option to only build a converter, that allows building the TLU-producer on servers wit afs access. 
` BUILD_USER_TLU_ONLY_CONVERTER` defaults to off and only effects the TLU. :+1:

### CODE REVIEW

**Comment by simonspa** [comment]
Either this should be supported for all modules or only called `USER_LTU_BUILD_CONVERTER` or so. Right now it gives the wrong impression that once could build all converters with it.

**Comment by lhuth** [comment]
That's why I said I can extend it to all modules if you agree with the approach

**Comment by simonspa** [comment]
I don't think that's a viable option because in many cases the converter depends on DAQ code (Caribou, CMS, ...) so it will be Flickwerk in any case.

`BUILD_USER_ONLY_CONVERTER_FOR_THOSE_MODULES_THAT_SUPPORT_IT` :smirk:

**Comment by lhuth** [comment]
Still, you could decide not to build the producers in these cases, right?

**Comment by lhuth** [comment]
works on lxplus :)

**Review by simonspa — DISMISSED** [review]

**Review by simonspa — APPROVED** [review]

**Pull request merged**
