### PR TITLE
Eudaq 2 devel

### PR DESCRIPTION
**Pull request by RPeschke**
EUDAQ 2 changes.

includes:
 new Processors
new Sync class
update to plugins system to give user more freedom on Synchronizing  data 
updated example Producer to be a state machine. easier starting point for users
updated converter to use processors: cleaner code
updated data collector do use processors: cleaner code 
updated data sender: now it is just another processor which can be used easier
updated test reader to use processors

updated Events to store multiple timestamps: breaks backward compatibility. we should discuss if we really want this.

### CODE REVIEW

**Comment by simonspa** [comment]
@RPeschke do you plan to solve the merge conflicts soonish? I will start reviewing after that...

**Comment by RPeschke** [comment]
@simonspa  I did not saw the push from @dreyling. I resolved the conflict by removing Jans changes

**Comment by simonspa** [comment]
Does not compile for me:

```
[ 65%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/processors/ProcessorWaitForEORE.cc.o
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:35:40: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
   std::atomic<int> m_numOfBoreEvents = 0, m_numOfEoreEvents = 0;
                                        ^
In file included from /home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:3:0:
/usr/include/c++/5/atomic:612:7: note: declared here
       atomic(const atomic&) = delete;
       ^
/usr/include/c++/5/atomic:616:17: note:   after user-defined conversion: constexpr std::atomic<int>::atomic(std::atomic<int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
                 ^
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:35:63: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
   std::atomic<int> m_numOfBoreEvents = 0, m_numOfEoreEvents = 0;
                                                               ^
In file included from /home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:3:0:
/usr/include/c++/5/atomic:612:7: note: declared here
       atomic(const atomic&) = delete;
       ^
/usr/include/c++/5/atomic:616:17: note:   after user-defined conversion: constexpr std::atomic<int>::atomic(std::atomic<int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
                 ^
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:6:18: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
 #define  waiting 0
                  ^
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:38:31: note: in expansion of macro ‘waiting’
   std::atomic<int> m_status = waiting;
                               ^
In file included from /home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:3:0:
/usr/include/c++/5/atomic:612:7: note: declared here
       atomic(const atomic&) = delete;
       ^
/usr/include/c++/5/atomic:616:17: note:   after user-defined conversion: constexpr std::atomic<int>::atomic(std::atomic<int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
                 ^
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc: In constructor ‘eudaq::Processor_WaitForEORE::Processor_WaitForEORE(int)’:
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:42:17: error: ‘MAXINT32’ was not declared in this scope
   m_lastEvent = MAXINT32;
                 ^
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc: In member function ‘virtual void eudaq::Processor_WaitForEORE::init()’:
/home/spanns/ilcsoft/eudaq/main/lib/processors/ProcessorWaitForEORE.cc:48:17: error: ‘MAXINT32’ was not declared in this scope
   m_lastEvent = MAXINT32;
                 ^
main/lib/CMakeFiles/EUDAQ.dir/build.make:2561: recipe for target 'main/lib/CMakeFiles/EUDAQ.dir/processors/ProcessorWaitForEORE.cc.o' failed
```

on
```
$ uname -a
Linux cmssimonnb 4.3.2-040302-generic #201512101931 SMP Fri Dec 11 00:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
```

**Comment by RPeschke** [comment]
new commit should fix this problem tried it on 

[peschke@nafhh-atlas04]~/xxl/eudaq/build% gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Gcc/gcc492_x86_64_slc6/slc6/x86_64-slc6-gcc49-opt/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.2/configure --prefix=/afs/.cern.ch/sw/lcg/contrib/gcc/4.9.2/x86_64-slc6 --with-system-zlib --disable-multilib --enable-languages=all
Thread model: posix
gcc version 4.9.2 (GCC)

**Comment by simonspa** [comment]
```
In file included from /home/spanns/ilcsoft/eudaq/monitors/onlinemon/./include/OnlineMonConfiguration.hh:17:0,
                 from /home/spanns/ilcsoft/eudaq/monitors/onlinemon/./include/SimpleStandardPlane.hh:22,
                 from /home/spanns/ilcsoft/eudaq/monitors/onlinemon/include/SimpleStandardEvent.hh:24,
                 from /home/spanns/ilcsoft/eudaq/monitors/onlinemon/include/BaseCollection.hh:14,
                 from /home/spanns/ilcsoft/eudaq/monitors/onlinemon/include/OnlineMonWindow.hh:33,
                 from /home/spanns/ilcsoft/eudaq/build/monitors/onlinemon/OnlineMonDict.h:34,
                 from /home/spanns/ilcsoft/eudaq/build/monitors/onlinemon/OnlineMonDict.cxx:17:
/usr/include/c++/5/sstream:300:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access
       struct __xfer_bufptrs
       ^
monitors/onlinemon/CMakeFiles/OnlineMon.dir/build.make:499: recipe for target 'monitors/onlinemon/CMakeFiles/OnlineMon.dir/OnlineMonDict.cxx.o' failed
make[2]: *** [monitors/onlinemon/CMakeFiles/OnlineMon.dir/OnlineMonDict.cxx.o] Error 1
CMakeFiles/Makefile2:1716: recipe for target 'monitors/onlinemon/CMakeFiles/OnlineMon.dir/all' failed
make[1]: *** [monitors/onlinemon/CMakeFiles/OnlineMon.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by RPeschke** [comment]
Hi,

which compiler do you use. as I said I just tried it with 4.9. can you try to make it with a clean build folder again.

cheers,
Richard

**Comment by simonspa** [comment]
Build folder was clean.
GCC is 5.2

```
$ cd build/ && rm -rf *
$ cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for C++11 compliance of compiler
-- Checking for C++11 compliance of compiler - available
-- Checking to see if CXX compiler accepts flag -std=c++11
-- Checking to see if CXX compiler accepts flag -std=c++11 - yes
-- Using gcc-specific preprocessor identifiers
CMake Warning at CMakeLists.txt:41 (MESSAGE):
  Your do not seem to have fetched the latest tags in your git repository --
  please consider running 'git fetch upstream'


-- Main EUDAQ library directory is clean (all changes have been commited).
-- Determined EUDAQ version v1.5.1+63~gfb365b4
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Looking for Root...
-- Found ROOT: /opt/root/bin/root (found version 5.34/19)
-- Looking for CMSPixel dependencies: pxarCore...
-- Found CMSPixel pxarCore library and headers.
-- Found Qt5Widgets: /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found Qt .., will build GUI executables
-- Looking for Root...
-- Found ROOT: /opt/root/bin/root (found version 5.34/19)
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
-- CMAKE_BINARY_DIR: /home/spanns/ilcsoft/eudaq/build
-- PROJECT_SOURCE_DIR: /home/spanns/ilcsoft/eudaq
-- This is CMake 3.2.2 (/usr/bin/cmake) running on Linux (4.3.2-040302-generic Ubuntu 15.10)
-- 64-bit compiler detected
-- Using GNU (/usr/bin/c++) version 5.2.1
-- Compiler Flags: -fPIC -O2 -std=c++11 
-- With COMPILE_DEFINITIONS = USE_EUDAQ2_VERSION;CPP11=1;EUDAQ_PLATFORM=PF_LINUX;EUDAQ_FUNC=__PRETTY_FUNCTION__ ;_GLIBCXX_USE_NANOSLEEP
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- *** Build Type RelWithDebInfo ***
-- *** Compiler Flags:  -fPIC -O2 -std=c++11
-- *** Compiler Flags:  -fPIC -O2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/spanns/ilcsoft/eudaq/build
```

**Comment by simonspa** [comment]
Sorry, seems to be a ROOT issue as mentioned here. Redeclaring `private` to `public` is still one of my favourite moves in the ROOT src code...
https://sft.its.cern.ch/jira/browse/ROOT-7440

**Comment by simonspa** [comment]
Okay, they seem to have fixed this issue in ROOT 5.34/34, so now everything compiles for me and looks nice.
I would say: merging.

**Pull request merged**
