### PR TITLE
upgrade SCTConvert to make it accept muilt blocks (muilt-planes) RawDataEvent 

### PR DESCRIPTION
**Pull request by Eyiliu**
In onlinemonitor, the default correl_minclustersize is changed to 1

### CODE REVIEW

**Comment by arummler** [comment]
Hi,
I have some comments:
a) I have made some big changes in the USBpixI4 converter plugin which are not yet finished and published. They deal mostly with having several producers of the same kind running at once and make also use of the configuration file information.
b) Having the possibility to rotate is useful, although it is the question where to put them. I think up to now people are doing it in eutelescope and I started to add it to the online monitor as well. But having the possibility in the converter plugin has certainly its merits. But for the usage in pixel testbeams it needs more functionality: Transformation of individual modules (as we had them mounted in different ways) and mirroring besides full rotation. I will try to make a sketch of that in my development branch. 
c) There will be also some changes to the OnlineMonitor but I don't see there a conflict.

**Comment by simonspa** [comment]
@Eyiliu @arummler is this fine for merging?

**Comment by arummler** [comment]
I will look into applying my changes to the master branch first. Needs a bit of time, probably this evening or tomorrow.

**Comment by Eyiliu** [comment]
@arummler  
Are you still working on clean up you changes? I expect to merger that with additional changes.

**Comment by arummler** [comment]
@Eyiliu I was sick the last days and got delayed. As I have a couple of deadlines this week I do not know whether I can prepare it. If you want we can merge it now, but I would change the configuration syntax later on again.

**Comment by arummler** [comment]
And it should be applied against 1.6 now.

**Comment by Eyiliu** [comment]
Yes, it should merge to1.6 .  I'm implimenting something like teperature Plot in onlinemonitor. When it is done,  I will PR them to 1.6 . 
I think I should close this PR, since  it is 1.5

**Pull request closed without merging**
